config/routes.rb
Rails.application.routes.draw do
  get 'tasks', to: 'tasks#index'

  get 'tasks/new', to: 'tasks#new'
  post 'tasks', to: 'tasks#create'

  get 'tasks/:id', to: 'tasks#show', as: :task

  get 'tasks/:id/edit', to: 'tasks#edit', as: :edit_task
  patch 'tasks/:id', to: 'tasks#update'

  delete 'tasks/:id', to: 'tasks#destroy', as: 'delete_task'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/article.rb
class Article < ApplicationRecord
end

app/models/task.rb
class Task < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/tasks_controller.rb
class TasksController < ApplicationController
  before_action :set_task, only: %i[show edit update destroy]

  def index
    @tasks = Task.all
  end

  def show
    @task.completed ? @msg = 'This task is completed' : @msg = 'This task is not completed yet'
  end

  def new
    @task = Task.new
  end

  def create
    Task.create!(task_params)
    redirect_to tasks_path
  end

  def edit; end

  def update
    @task.update!(task_params)
    redirect_to task_path(@task.id)
  end

  def destroy
    @task.destroy!
    redirect_to tasks_path
  end

  private

  def task_params
    params.require(:task).permit(:title, :details, :completed)
  end

  def set_task
    @task = Task.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tasks_helper.rb
module TasksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsTaskManager</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <link href="https://fonts.googleapis.com/css?family=Open+Sans" rel="stylesheet">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container-fluid mt-5">
      <%= yield %>
    </div>
  </body>
</html>

app/views/tasks/edit.html.erb
<h1> Edit Task </h1>

<%= form_for @task do |f| %>

  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :details %> <br>
  <%= f.text_field :details %> <br>
  <%= f.check_box :completed %>
  <%= f.label 'Check me out' %> <br>
  <%= f.submit %> <br>

<% end %>

app/views/tasks/index.html.erb
<h1>My Tasks</h1>

<% @tasks.each do |task| %>
  <div class="form-check">
    <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
    <label class="form-check-label" for="defaultCheck1"><%= link_to task.title, task %></label>
    <%= link_to delete_task_path(task.id), method: "DELETE" do %>
      <%= fa_icon "trash-o" %>
    <% end %>
  </div>
<% end %>

<hr>

<%= link_to tasks_new_path do %>
  <%= fa_icon "plus" %> Add a new task
<% end %>

app/views/tasks/new.html.erb
<h1> New Task </h1>

<%= form_for @task do |f| %>

  <%= f.label :title %> <br>
  <%= f.text_field :title %> <br>
  <%= f.label :details %> <br>
  <%= f.text_field :details %> <br>
  <%= f.submit %> <br>

<% end %>

app/views/tasks/show.html.erb
<div class="text-inline">
  <h1><%= @task.title %></h1>
  <div class="btn btn-light">
    <%= link_to '<i class="fa fa-pencil" aria-hidden="true"> Edit this task</i>'.html_safe, edit_task_path(@task.id)%>
  </div>
</div>

<p id="details"><%= @task.details %></p>

<div class="form-check">
  <input class="form-check-input" type="checkbox" value="" id="defaultCheck1">
  <label class="form-check-label" for="defaultCheck1"><%= @msg %></label>
</div>

<hr>

<%= link_to 'Back to list', tasks_path %>

app/views/tasks/update.html.erb
<h1>Tasks#update</h1>
<p>Find me in app/views/tasks/update.html.erb</p>